Algoritmo "Orientacao a Objetos - Tipos"
tipo
cadastroCliente = registro
   nome: caractere
   rg: caractere
   idade: caractere

fimregistro

Var
cliente1: cadastroCliente

Inicio
Escreval("Digite seu nome: ")
Leia(cliente1.nome)

Escreval("Digite seu rg: ")
Leia(cliente1.rg)

Escreval("Digite sua idade: ")
Leia(cliente1.idade)

Escreval("Nome: ", cliente1.nome, "- RG: ", cliente1.rg, "- Idade: ", cliente1.idade)

Fimalgoritmo