Algoritmo "Escolha"

Var
voto: inteiro

Inicio
Escreval("Digite o voto: ")
leia(voto)

Escreval("Apuração usando estrutura se/senao")

se voto = 20 entao
 Escreval("Você votou em Marcelo Bernart")
senao
se voto = 30  entao
 Escreval("Você votou no Pernalonga")
senao
se voto = 40  entao
 Escreval("Você votou em Patolino")
senao
 Escreval("Você votou nulo")
fimse
fimse
fimse

// Usando a estrutura condicional Escolha

Escreval("Apuração usando estrutura Escolha")
Escolha voto
caso 20
     Escreval("Você votou em Marcelo Bernart")
caso 30
     Escreval("Você votou no Pernalonga")
caso 40
 Escreval("Você votou em Patolino")
outrocaso
 Escreval("Você votou nulo")
fimescolha



Fimalgoritmo